### ISSUE TITLE
DCO check fails with commits not in PR, from another author

### ISSUE THREAD

**Issue by kieckhafer** [probot/dco#115]
We've been seeing this issue a lot recently (I've personally seen it three times in the past week, and others on my team have brought it up as well). We create a new branch off our default `develop` branch, make a few changes that are DCO approved, and yet DCO bot fails saying commits by other developers are not signed off.

[This PR is the latest example](https://github.com/reactioncommerce/reaction/pull/5307):
1. I made a new branch off our main branch
1. I made all my changes in three commits (all signed-off)
https://github.com/reactioncommerce/reaction/pull/5307/commits/16e3a71e64ec793f3f3f71b34174172cbbf70d8c 
https://github.com/reactioncommerce/reaction/pull/5307/commits/90b6757204419ec6ca58e215162f26e2fb5febb9
https://github.com/reactioncommerce/reaction/pull/5307/commits/035b5747f6844ee982fa99598360b873e2ffd2b7
1. I made a PR, and am receiving a failed DCO check, from another developer with commits not in this PR: https://github.com/reactioncommerce/reaction/pull/5307/checks?check_run_id=166954847
![image](https://user-images.githubusercontent.com/4482263/61080664-6b4e4380-a3da-11e9-8dfe-384f2100e7d2.png)

UPDATE:
Another example just popped up: https://github.com/reactioncommerce/reaction/pull/5320/checks?check_run_id=167950629

**Comment by hiimbex** [comment]
It seems to me the issue occurs on only the first 'set' of commits pushed to the PR? We use https://developer.github.com/v3/repos/commits/#compare-two-commits in order to access the list of commits. Maybe for some reason this branch is also returning its base commit as well and causing the issue? Never seen this behavior before, maybe GitHub/the DCO is confused by your branch off a branch workflow?

I'm sorry I can't really investigate this further, but happy to review PRs. For now a viable workflow seems just to be push another commit to retrigger the check?
