### ISSUE TITLE
DCO fail to verify sign off

### ISSUE THREAD

**Issue by vinodkahuja** [probot/dco#140]
DCO fail to verify the sign off even though the signoff is verified. 

![image](https://user-images.githubusercontent.com/25468243/97925112-6f684800-1d26-11eb-9869-b905cc9fb16e.png)

**Comment by hiimbex** [comment]
Looks like this was resolved by an override - glad to see that feature being useful!

Unfortunately not being able to look into the PR makes it hard for me to debug - couldve been an inconsistency in name or email, or a true bug. Going to close for now since I can't investigate further, but please feel free to open another issue if this happens again
