### ISSUE TITLE
DCO checks not happening since 2017-08-31 or 2017-09-01

### ISSUE THREAD

**Issue by tykeal** [probot/dco#24]
We've got several projects that have the DCO probot integration configured and since sometime on at least Thursday (2017-08-31) or Friday (2017-09-01) last week all the checks are just sitting there with 'DCO — Waiting for status to be reported' for the check.

Two things related to this:
1) Any idea how to retrigger checks that are integrations?
2) Any idea when this is going to be fixed?

**Comment by hiimbex** [comment]
@bkeepers This is definitely due to deprecating `(context, event)` to `context`, the updates do exist in https://github.com/probot/dco/pull/19 but there are still no tests 😬 

I was also gonna wait to figure that out to swap to standard lint. 

Also not sure about how to retrigger events like that other than manually on our end?

@tykeal We can probably get this fixed pretty quickly, given that I know what broke. :)

**Comment by tykeal** [comment]
@hiimbex thanks. In the mean time, I guess it's visual inspection time and using administrative super powers for merges...

**Comment by hiimbex** [comment]
Also re: this sentry error: https://sentry.io/probot/dco/issues/343943452/

**Comment by bkeepers** [comment]
@tykeal Sorry about the issue. A fix is deployed so it should be working going forward. I just realized earlier today that error-reporting wasn't set up for this app and enabled it, so we should catch issues sooner in the future.

At the moment, the easiest way to re-trigger the checks is to push a commit (`git commit --allow-empty -s -m 'Force DCO check'` to add an empty commit). If that doesn't work, you can link to the repos that are affected and we can try to find and redeliver the webhook events for those repositories.

We'll start working on a better way to re-trigger the checks.
