### ISSUE TITLE
Error: Validation Failed

### ISSUE THREAD

**Issue by bkeepers** [probot/dco#29]
https://sentry.io/probot/dco/issues/345257325/

```
Error: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"description","message":"description is too long (maximum is 140 characters)"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}

Error: {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"description","message":"description is too long (maximum is 140 characters)"}],"documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
```

Affecting this PR: https://github.com/tunnckoCore/parse-function/pull/49 (heads up @charlike)

**Comment by charlike** [comment]
It fails, because the Renovate App lowercases the commit message by default, so it is `signed-off-by` instead of `Signed-off-by`.

But error message is strange anyway.. Why is "description is too long"? It's not too long, imo.

You can close this, we working on fixes, thanks :)

**Comment by bkeepers** [comment]
@hiimbex the description being too long is from changes in #19. We should probably truncate it either way.

> It fails, because the Renovate App lowercases the commit message by default, so it is `signed-off-by` instead of `Signed-off-by`.

We should also handle this case.

**Comment by hiimbex** [comment]
Hmm, the description too long part seems like it might have been affected by my recent changes, since now we actually show it in the message. @charlike description in this error message refers to a field we pass into the GitHub API.

So the bot acted correctly on the first commit, since we expect a case sensitive `Signed-off-by` message, but on the second commit, the message would've become 
> The sign-off is missing. Expected charlike and {email} but got Signed-off-by: renovate[bot] <renovate[bot]@users.noreply.github.com>

The above is 132 characters, but I assume the email was longer. Easiest solution is just showing the issues with the most recent commit instead of trying to stack them? ie:
> ~~The sign-off is missing.~~ Expected charlike and {email} but got Signed-off-by: renovate[bot] <renovate[bot]@users.noreply.github.com>

Still someone could have a very long username and email potentially and I really hadn't considered that case. Any ideas @bkeepers? I'll open a PR to just replace the description field with the most recent message instead of trying to append to it in the meantime.

**Comment by hiimbex** [comment]
I'm not super familiar with DCO standards and whether this is acceptable to ignore the casing, but you think we should swap the regex around `Signed-off-by` the be case insensitive?

**Comment by bkeepers** [comment]
Whatever is easiest. Just truncate the message?

I think long-term the solution is to link to a page like #27 and show details for each commit.

**Comment by hiimbex** [comment]
👍 yea that is definitely a better long term solution. In the meantime I'll implement the easy solution, and in the near future add some checking to confirm the description is less than 140 characters before passing it in. The second part isn't hard, I'm just not sure the best way to cut it off, maybe just the end?

**Comment by charlike** [comment]
I vote for case sensitive `Signed-off-by`. I'm not familiar much with that standard too, but i didn't noticed it lowercased nowhere, so probably it must be with capital S.

**Comment by hiimbex** [comment]
Honestly, I think having me signing all my commits `sIgNeD-OfF-bY: ` is just as in agreement with the DCO as `Signed-off-by: `. And I think given the future takeover of bots, there's potential for weird casing situations, so the more I think about it, the more I'm in favor of case insensitivity. But if there's any actual DCO standard regarding the topic, I'd defer to that.

**Comment by charlike** [comment]
Yea, i'm agree. But probably should ask someone from the Linux community and/or other more heavy DCO users.
