### ISSUE TITLE
DCO is too strict on the submitter's name

### ISSUE THREAD

**Issue by cclauss** [probot/dco#43]
https://github.com/hyperledger/sawtooth-core/pull/1002

**Comment by bkeepers** [comment]
Just to clarify, @cclauss, you're suggesting that the signoff name shouldn't have to match the commit author? Here is the commit in question:

```
From 376dee629950d001716f46df7be41713c16ae531 Mon Sep 17 00:00:00 2001
From: cclauss <cclauss@bluewin.ch>
Date: Sat, 14 Oct 2017 09:35:11 +0200
Subject: [PATCH] Remove unused method _generate_id()

Implement  #882 in a way that satisfies the DCO bot.

Signed-off-by: Chris Clauss <cclauss@bluewin.ch>
```

The challenge is that using `git commit --signoff` will use whatever is configured in git for the author field, and the DCO documentation recommends using your full name.

From the [kernel docs](https://kernelnewbies.org/UpstreamMerge/SubmittingPatches):

> ```
> then you just add a line saying
> 
>        Signed-off-by: Random J Developer <random@developer.example.org>
>
> using your real name (sorry, no pseudonyms or anonymous contributions.)
> ```

So while the docs don't say anything about what should be included in the author field, I would expect it to be the same since it is the default value for the `--signoff` flag.

Thoughts?

cc @mlinksva @mkdolan @caniszczyk

**Comment by mkdolan** [comment]
I believe all the tool checks is that the author's name matches the signed-off-by name. Is that correct @bkeepers? 

By example, the Linux kernel community manually checks this, so they know it's not an anonymous person or pseudonym, but I'm not sure how you can do what Chris suggests. One way might be to check for the author name to match or the prefix on the email address to match the signed-off-by name. (just thinking out loud a way around the error Chris points to).

Another issue asked if the author and signed-off-by had to come from the same person (which is not required), but I'm not sure where things ended up there.

**Comment by cclauss** [comment]
> So while the docs don't say anything about what should be included in the author field

Really?  I thought that it said:

> using your real name (sorry, no pseudonyms or anonymous contributions.)

My real name is Chris Clauss and username/handle/pseudonym is cclauss.  The current DCO seem to be ensuring that I do not sign-off using my real name but that I use a pseudonym instead.

**Comment by hiimbex** [comment]
@cclauss when you go into your command line what is you git user's name? As in: `$ git config --global user.name`. The DCO check is based off of this name, so I'm curious if you set it to be your real name as opposed to your handle.

**Comment by cclauss** [comment]
Ahhhh...  This is the best question yet.  The PR in question was the deletion of four contiguous lines of code.  I really did not need and did not choose to use git in the execution of this PR.  I merely used the GitHub web ui to edit the file, delete the four lines, and create a signature line to match the Random J. Developer example above.  Given that probot comes out of GitHub, I had thought that it would would support the use of the GitHub web ui in addition to the commandline .  Perhaps the best approach would be to add a sign-off checkbox to the GitHub web ui.

**Comment by hiimbex** [comment]
Upon clicking on your profile @cclauss, it appears you don't have a first/last name set, so the only name GitHub knows you as is cclauss, which was _not_ what you signed off as, which is why the DCO check failed.

I think there's an interesting take-away about whether or not git usernames (ie mine is hiimbex) could count as a sign off name, but the kermel docs say:
> using your real name (sorry, no pseudonyms or anonymous contributions.)

So since I think this specific instance is just user error, I'm gonna close this out.

**Comment by cclauss** [comment]
Makes sense.  Thanks to all.

**Comment by mkdolan** [comment]
Thanks for working through this Chris.
