### ISSUE TITLE
Easier way to opt-out only a few repositories

### ISSUE THREAD

**Issue by diml** [probot/dco#76]
Hi,

I started using this application for a few repositories and it's really useful, thanks!

I would now like to enable it for my company's github organisation that has both public and private repositories. I want the checks for all the public repositories, but not for the private ones. Currently the only way to do so is to manually specify the list of all public repositories, which is painful as we have about 150 public repositories, with new repositories being created from now and then.

For my case, the best would be to enable the checks via a setting in the `.github/dco.yml` file.

**Comment by hiimbex** [comment]
Glad you like DCO!

We love this idea and are working on it over in https://github.com/probot/probot-config, specifically see conversations in https://github.com/probot/probot-config/pull/7 and https://github.com/probot/probot-config/issues/1. Also see https://github.com/probot/probot/issues/258 for the original conversation. The issue of org wide configuration for apps is a larger ongoing probot problem, so we want to create standard patterns for this configuration for all our apps to follow.

If you have further specific feedback/ideas about this, I'd appreciate if you could throw them in an issue in https://github.com/probot/probot-config. Gonna close this out though, since I'd prefer to keep the conversation on this topic over there :)
